env:
    profiles:
        active: prod
isDebug: true
server:
    port: 8080
    bossGroupThreads: 1
    workerGroupThreads: 10
    maxContentLength: 65535
database:
    url: jdbc:mysql://localhost/dev_db
redis:
    database: 0
    port: 6379
thread:
    pool: 10
    profiles: dev
